### ISSUE TITLE
Cannot use this command

### ISSUE THREAD

**Issue by kompiro** [kompiro/pr-summary#2]
Runs this command, shows error below.

```
module.js:328
    throw err;
    ^

Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/var/nodebrew/node/v4.2.6/lib/node_modules/pr-summary/lib/pr-summary.js:15:16)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
```

**Comment by kompiro** [comment]
Fixed
